# Generated by Django 6.0.2 on 2026-03-13 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_loan_interest_rate'),
        ('members', '0002_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='beneficiary',
            field=models.ForeignKey(blank=True, help_text='Leave blank if this loan is for you.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefited_loans', to='members.member'),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_on_behalf',
            field=models.BooleanField(default=False, verbose_name='Applying on behalf of someone else?'),
        ),
    ]
