# Generated by Django 6.0.2 on 2026-02-12 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(help_text='Format: 07XX XXX XXX', max_length=15, unique=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('monthly_contribution_amount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
