# Generated by Django 6.0.2 on 2026-03-13 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='Monthly General Meeting', max_length=100)),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings_attended', to='members.member')),
            ],
        ),
    ]
