# Generated by Django 6.0.2 on 2026-03-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='monthly_contribution_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
