# Generated by Django 6.0.2 on 2026-03-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_monthly_contribution_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='monthly_contribution_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
